# -*- coding: utf-8 -*-
"""HydroTrack_modele-IA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kYMleS5ayHB8JtG4B5rme1Jl4Isl9ykV
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import IsolationForest

df = pd.read_csv(
    "Donnee_compteur_SEP.csv",
    sep=";",
    encoding="cp1252"
)

df.columns = df.columns.str.strip().str.replace("\n", "").str.replace("\r", "")

df["Horodatage"] = pd.to_datetime(df["Horodatage"], dayfirst=True)
df = df.sort_values("Horodatage")
print(df.columns)

compteurs = [
    c for c in df.columns
    if "_" not in c and c != "Horodatage"
]

data_all = []

for compteur in compteurs:

    q_col = f"{compteur}_Qualite"

    if compteur not in df.columns or q_col not in df.columns:
        continue

    d = df[["Horodatage", compteur, q_col]].copy()

    # garder uniquement GOOD
    d = d[d[q_col] == "GOOD"]

    # conversion propre
    d[compteur] = pd.to_numeric(d[compteur], errors="coerce")

    # supprimer NaN
    d = d.dropna(subset=[compteur])

    # calcul consommation
    d["delta_val"] = d[compteur].diff()
    d["delta_t"] = d["Horodatage"].diff().dt.days

    d["conso_jour"] = d["delta_val"] / d["delta_t"]

    # nettoyage logique
    d = d.dropna()
    d = d[d["conso_jour"] >= 0]

    d["capteur"] = compteur

    data_all.append(d)

df_conso = pd.concat(data_all, ignore_index=True)

df_conso["conso_log"] = np.log1p(df_conso["conso_jour"])

model = IsolationForest(
    n_estimators=300,
    random_state=42
)

df_conso["anomaly"] = model.fit_predict(df_conso[["conso_log"]])
df_conso["score"] = model.decision_function(df_conso[["conso_log"]])

def compute_levels(group):
    return pd.Series({
        "q90": group["score"].quantile(0.10),
        "q97": group["score"].quantile(0.03),
        "q99": group["score"].quantile(0.01),
    })

thresholds = df_conso.groupby("capteur").apply(compute_levels)
df_conso = df_conso.join(thresholds, on="capteur")

def alert(row):
    if row["score"] < row["q99"]:
        return "🔴 ROUGE"
    elif row["score"] < row["q97"]:
        return "🟠 ORANGE"
    elif row["score"] < row["q90"]:
        return "🟡 JAUNE"
    return "NORMAL"

df_conso["alerte"] = df_conso.apply(alert, axis=1)

print("Nb total de points :", len(df_conso))
print("Nb de capteurs :", df_conso["capteur"].nunique())

df_conso["alerte"].value_counts()

capteur_test = "NOG 1SEP992QD"

df_conso[df_conso["capteur"] == capteur_test][
    ["Horodatage", "conso_jour", "score", "alerte"]
].sort_values("Horodatage")

import matplotlib.pyplot as plt

d = df_conso[df_conso["capteur"] == capteur_test]

plt.figure(figsize=(12,5))
plt.plot(d["Horodatage"], d["conso_jour"], label="Consommation")
plt.scatter(
    d[d["alerte"] != "NORMAL"]["Horodatage"],
    d[d["alerte"] != "NORMAL"]["conso_jour"],
    label="Alertes"
)
plt.legend()
plt.title(capteur_test)
plt.show()

plt.figure(figsize=(6,4))
plt.hist(d["score"], bins=30)
plt.title("Distribution des scores")
plt.show()

split_date = df_conso["Horodatage"].quantile(0.7)

train = df_conso[df_conso["Horodatage"] <= split_date]
test  = df_conso[df_conso["Horodatage"] > split_date]

model = IsolationForest(n_estimators=300, random_state=42)
model.fit(train[["conso_log"]])

test["score"] = model.decision_function(test[["conso_log"]])

d_sim = d.copy()
d_sim.loc[d_sim.index[-3:], "conso_jour"] *= 3
d_sim["conso_log"] = np.log1p(d_sim["conso_jour"])

d_sim["score_sim"] = model.decision_function(d_sim[["conso_log"]])